stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: registry.gitlab.com/your-namespace/your-project/test2-app
  IMAGE_TAG: $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - echo "Building Docker image..."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "Deploying to Kubernetes..."
    - kubectl config set-cluster my-cluster --server=$KUBE_SERVER --certificate-authority=ca.crt --embed-certs=true
    - kubectl config set-credentials gitlab-ci --token=$KUBE_TOKEN
    - kubectl config set-context my-context --cluster=my-cluster --user=gitlab-ci --namespace=test2
    - kubectl config use-context my-context
    - kubectl set image deployment/test2-deployment test2=$IMAGE_TAG --record
  environment:
    name: production
  only:
    - main
